spring:
  h2:
    console.enabled: true
  datasource:

    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  date:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


jwt:
  issuer: test@test.com

  secret_key: ${JWT_SECRET_KEY}
  expiration: 60000 # 1 day
  refresh-token:
    expiration: 604800000 # 7 days
